version: '3'

services:        
    sonarr:
        image: linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./config:/config
            - /where_your_tv_shows_are:/tv
            - /your_transmission_completed_folder:/downloads
        ports:
            - 8990:8989
        restart: unless-stopped
        network_mode: bridge