version: '3'

services:
    prowlarr:
        image: ghcr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./config:/config
        ports:
            - 9696:9696
        restart: unless-stopped
