version: '3'

services:
    lidarr:
        image: ghcr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./config:/config
            - /where_you_store_your_music:/music
            - /your_transmission_completed_folder:/downloads
        ports:
            - 8686:8686
        restart: unless-stopped